import requests
import json
from time import sleep

import os
from dotenv import load_dotenv
load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
APPLICATION = os.getenv('DISCORD_APPLICATION')

url = "https://discord.com/api/v8/applications/" + APPLICATION + "/commands"
headers = {"Authorization": "Bot " + TOKEN}

# Get commands
with open("commands.json") as f:
    commands = f.read()

# Insert autogenerated language list into json commands
with open("language_options.json") as f:
    language_options = f.read()

commands_complete = commands.replace("\"LANGUAGE_OPTIONS\"", language_options)

# Insert autogenerated font list into json commands
with open("../fonts.json") as f:
    fonts = json.load(f)

fonts = [{"name": x, "value": x} for x in fonts.keys()]
fonts = json.dumps(fonts)
commands_complete = commands_complete.replace("\"FONTS\"", fonts)

json_commands = json.loads(commands_complete)

# Remove currently registered commands
for command in requests.get(url, headers=headers).json():
    print("Deleting", command)
    print(requests.delete(url + "/" + command["id"], headers=headers))
    sleep(5)

# Register commands
for command in json_commands:
    print("Registering", command)
    print(requests.post(url, headers=headers, json=command))
    sleep(5)

# Print current commands
for command in requests.get(url, headers=headers).json():
    print("Exists", command)

