# generated by datamodel-codegen:
#   filename:  fingerspelling.json

from __future__ import annotations

from typing import NotRequired

from typing_extensions import TypedDict


class FieldSchema3(TypedDict, closed=True):
    language: str
    """The language of the sign."""
    sign: NotRequired[str]
    """The name of the sign such that it could be found in a sign language dictionary."""


class FieldSchema5(TypedDict, closed=True):
    """Scripts for representing a sign as characters."""

    fsw: str
    """The [Formal SignWriting](https://en.wikipedia.org/wiki/SignWriting) representation of the sign."""
    swu: str
    """The [SignWriting with Unicode](https://en.wikipedia.org/wiki/SignWriting) representation of the sign."""


class FieldSchema8(TypedDict, closed=True):
    """Videos of the sign being performed, by format."""

    gif: str
    """A link to a gif of the sign being signed."""
    mp4: str
    """a link to an mp4 of the sign being signed."""


class Parameters(TypedDict, closed=True):
    """Partly localized descriptions of how a sign is signed."""

    handshape: NotRequired[str]
    """The shape of the hand when signing, identified by its name in ASL. Should not be translated in any language other than Toki Pona"""
    movement: NotRequired[str]
    """The motion of the hand when signing."""
    placement: NotRequired[str]
    """The placement of the hand when signing."""
    orientation: NotRequired[str]
    """The orientation of the hand when signing."""


class FieldSchema12(TypedDict, closed=True):
    parameters: Parameters
    """Partly localized descriptions of how a sign is signed."""


class Fingerspelling(TypedDict, closed=True):
    """Info on a fingerspelling sign."""

    id: str
    """A unique name for the fingerspelling which is also a gloss."""
    is_two_handed: bool
    """Whether the sign is two-handed or not."""
    etymology: list[FieldSchema3]
    """Unlocalized etymological values regarding this sign's origin"""
    signwriting: FieldSchema5
    video: NotRequired[FieldSchema8]
    translations: FieldSchema12
