# generated by datamodel-codegen:
#   filename:  fonts.json

from __future__ import annotations

from enum import StrEnum
from typing import NotRequired

from typing_extensions import TypedDict


class FieldSchema15(StrEnum):
    """
    the writing system this font uses as its script
    """

    sitelen_pona = 'sitelen pona'
    sitelen_sitelen = 'sitelen sitelen'
    alphabet = 'alphabet'
    syllabary = 'syllabary'
    logography = 'logography'
    tokiponido_alphabet = 'tokiponido alphabet'
    tokiponido_syllabary = 'tokiponido syllabary'
    tokiponido_logography = 'tokiponido logography'


class FieldSchema16(TypedDict, closed=True):
    fontfile: NotRequired[str]
    """a link to the font file published by the original author (not the mirror on the Linku Project's GitHub)"""
    repo: NotRequired[str]
    """a link to a web hosted repository of this font's source files (usually hosted on GitHub or GitLab)"""
    webpage: NotRequired[str]
    """a link to this font's home page, usually showcasing its features and usage/installation"""


class FieldSchema1(TypedDict, closed=True):
    """Info on a font for Toki Pona"""

    id: str
    """The font's unique ID, identifying it among other fonts"""
    author: list[str]
    """a list of this font's authors"""
    features: list[str]
    """a list of features this font supports"""
    filename: str
    """the name of the file this font is stored in at https://github.com/lipu-linku/ijo"""
    last_updated: str
    """the rough date of this font's last update"""
    license: str
    """an SPDX expression describing this font's license: https://spdx.org/licenses/"""
    ligatures: bool
    """whether this font supports ligatures"""
    name: str
    """this font's name"""
    style: str
    """the general style of this font"""
    ucsur: bool
    """whether this font conforms to the UCSUR standard: https://www.kreativekorp.com/ucsur/charts/sitelen.html"""
    version: str
    """the current version of this font"""
    writing_system: FieldSchema15
    links: FieldSchema16


type Fonts = dict[str, FieldSchema1]
"""A raw data object containing all fonts data in Linku"""
