# generated by datamodel-codegen:
#   filename:  glyph.json

from __future__ import annotations

from enum import StrEnum
from typing import NotRequired

from typing_extensions import TypedDict


class UsageCategory(StrEnum):
    """
    The glyph's usage category, derived from the data of the annual Linku glyph survey.
    """

    core = 'core'
    common = 'common'
    uncommon = 'uncommon'
    obscure = 'obscure'
    sandbox = 'sandbox'


class Translations(TypedDict, closed=True):
    commentary: str
    """Localized commentary on this glyph, such as history, clarifications, or trivia."""
    etymology: str
    """Localized etymology of this glyph."""
    names: list[str]
    """A list of names used to refer to this sitelen pona glyph"""


class Glyph(TypedDict, closed=True):
    id: str
    """A unique identifier for the glyph. Named after its primary word and numbered in order of coining or attestation."""
    word: str
    """The toki pona word which is written with this glyph."""
    word_id: str
    """The Linku id of the toki pona word this glyph writes."""
    usage_category: UsageCategory
    """The glyph's usage category, derived from the data of the annual Linku glyph survey."""
    author: list[str]
    """The name or names of those involved in creating this glyph."""
    author_source: NotRequired[str]
    """The source or origin of this glyph, often a URL."""
    creation_date: str
    """When this glyph was created, to precision known"""
    see_also: list[str]
    """A list of related glyphs by ID"""
    primary: bool
    """Whether this glyph is the main glyph used to write the toki pona word in `word`"""
    parent_id: NotRequired[str]
    """The primary glyph which this glyph is considered to share its form with."""
    deprecated: bool
    """Whether this glyph is considered deprecated by its author(s)."""
    image: NotRequired[str]
    """A URL to an image of the sitelen pona glyph."""
    svg: NotRequired[str]
    """A URL to an SVG of the sitelen pona glyph."""
    ligature: NotRequired[str]
    """The specific numerical ligature used to render this sitelen pona glyph."""
    alias_ligatures: NotRequired[list[str]]
    """All non-numerical ligature used to render this sitelen pona glyph."""
    ucsur: NotRequired[str]
    """The UCSUR codepoint used to render this specific sitelen pona glyph."""
    usage: dict[str, float]
    """The percentage of respondents to the annual Linku word survey who report to use this glyph, by the date of the survey."""
    translations: Translations
