# generated by datamodel-codegen:
#   filename:  language.json

from __future__ import annotations

from typing import Literal, NotRequired

from typing_extensions import TypedDict

type FieldSchema0 = str
"""A unique identifier for an object in Linku. Generally named after the object."""


class Name(TypedDict, closed=True):
    en: str
    """The name of the language in English."""
    endonym: str
    """The name of the language in that language. Prefer if available."""
    tok: NotRequired[str]
    """The name of the language in Toki Pona."""


class Language(TypedDict, closed=True):
    id: str
    """The language's code in Crowdin. Usually its 2 or 3 letter code."""
    locale: str
    """The locale code corresponding to the language."""
    direction: Literal['ltr'] | Literal['rtl']
    """The direction of the language's script."""
    name: Name
