# generated by datamodel-codegen:
#   filename:  signs.json

from __future__ import annotations

from typing import NotRequired

from typing_extensions import TypedDict


class FieldSchema5(TypedDict, closed=True):
    language: str
    """The language of the sign."""
    sign: NotRequired[str]
    """The name of the sign such that it could be found in a sign language dictionary."""


class FieldSchema7(TypedDict, closed=True):
    """Scripts for representing a sign as characters."""

    fsw: str
    """The [Formal SignWriting](https://en.wikipedia.org/wiki/SignWriting) representation of the sign."""
    swu: str
    """The [SignWriting with Unicode](https://en.wikipedia.org/wiki/SignWriting) representation of the sign."""


class FieldSchema10(TypedDict, closed=True):
    """Videos of the sign being performed, by format."""

    gif: str
    """A link to a gif of the sign being signed."""
    mp4: str
    """a link to an mp4 of the sign being signed."""


class Parameters(TypedDict, closed=True):
    """Partly localized descriptions of how a sign is signed."""

    handshape: NotRequired[str]
    """The shape of the hand when signing, identified by its name in ASL. Should not be translated in any language other than Toki Pona"""
    movement: NotRequired[str]
    """The motion of the hand when signing."""
    placement: NotRequired[str]
    """The placement of the hand when signing."""
    orientation: NotRequired[str]
    """The orientation of the hand when signing."""


class FieldSchema14(TypedDict, closed=True):
    icons: str
    """Localized descriptions of the thing a sign represents."""
    parameters: Parameters
    """Partly localized descriptions of how a sign is signed."""


class FieldSchema1(TypedDict, closed=True):
    """Info on a Luka Pona sign"""

    id: str
    """A unique name for the fingerspelling which is also a gloss."""
    is_two_handed: bool
    """Whether the sign is two-handed or not."""
    etymology: list[FieldSchema5]
    """Unlocalized etymological values regarding this sign's origin"""
    signwriting: FieldSchema7
    video: NotRequired[FieldSchema10]
    translations: FieldSchema14
    definition: str
    """The definition of the sign as a single toki pona word."""
    new_gloss: str
    """The more recent, preferred gloss for this sign."""
    old_gloss: str
    """The older gloss for this sign, similar to `id`."""
    old_id: str
    """Previous, malformed id for the sign."""


type Signs = dict[str, FieldSchema1]
"""A raw data object containing information about Luka Pona signs"""
