# generated by datamodel-codegen:
#   filename:  words.json

from __future__ import annotations

from enum import StrEnum
from typing import NotRequired

from typing_extensions import TypedDict


class FieldSchema8(StrEnum):
    """
    Which official Toki Pona book was this word featured in, if any.
    """

    pu = 'pu'
    ku_suli = 'ku suli'
    ku_lili = 'ku lili'
    none = 'none'


class FieldSchema9(StrEnum):
    """
    The period of time in which this word was coined, relative to the publication of the first two official Toki Pona books
    """

    pre_pu = 'pre-pu'
    post_pu = 'post-pu'
    post_ku = 'post-ku'


class FieldSchema36(StrEnum):
    """
    The word's usage category, derived from the data of the annual Linku word survey.
    """

    core = 'core'
    common = 'common'
    uncommon = 'uncommon'
    obscure = 'obscure'
    sandbox = 'sandbox'


class FieldSchema51(TypedDict, closed=True):
    commentary: str
    """Localized commentary on this word, such as history, clarifications, or trivia."""
    etymology: str
    """Localized etymology of this word."""
    definition: str
    """Localized definition of this word."""


class FieldSchema38Item(TypedDict, closed=True):
    """Audio files of the words pronounced out loud"""

    author: str
    """The author of the audio file in `link`."""
    link: str
    """A link to the audio file for the word, pronounced by `author`."""


class FieldSchema42(TypedDict, closed=True):
    en: str
    """The word's definition in the English edition of Toki Pona: The Language of Good"""
    fr: str
    """The word's definition in the French edition of Toki Pona: The Language of Good"""
    de: str
    """The word's definition in the German edition of Toki Pona: The Language of Good"""
    eo: str
    """The word's definition in the Esperanto edition of Toki Pona: The Language of Good"""


class FieldSchema20(TypedDict, closed=True):
    """Non-Linku resources related to the specific word, such as wiki links."""

    sona_pona: NotRequired[str]
    """A link to the word's page on sona.pona.la, a Toki Pona wiki. May redirect for words with references but no dedicated page."""
    lipamanka_semantic: NotRequired[str]
    """A link to lipamanka's description of the word's semantic space."""


type FieldSchema41 = FieldSchema42
"""The definition of the word in specific language editions of Toki Pona: The Language of Good"""


class FieldSchema24(TypedDict, closed=True):
    """Ways of representing this word via text/computers"""

    sitelen_emosi: NotRequired[str]
    """The sitelen emosi representation of this word, a script for writing Toki Pona using emoji"""
    sitelen_jelo: NotRequired[list[str]]
    """One or more example emojis for how the word can be written in sitelen jelo"""
    ligatures: NotRequired[list[str]]
    """A list of sitelen Lasina representations of the word, used by ligature fonts to visually convert latin characters into sitelen pona"""
    sitelen_sitelen: NotRequired[str]
    """A URL pointing to an image of this word's sitelen sitelen hieroglyphic block"""
    ucsur: NotRequired[str]
    """The UCSUR codepoint for this word."""


class FieldSchema1(TypedDict, closed=True):
    """General info on a Toki Pona word"""

    id: str
    """A unique identifier for the word. May have an integer to distinguish words with the same spelling but distinct coinings."""
    word: str
    """The latin alphabet representation of the word."""
    author_verbatim: NotRequired[str]
    """The author's original definition, taken verbatim in their words"""
    author_source: NotRequired[str]
    """The source or origin of this glyph, often a URL."""
    book: FieldSchema8
    coined_era: FieldSchema9
    creation_date: str
    """When this word was coined, to precision known."""
    author: list[str]
    """The name or names of those involved in creating this word."""
    ku_data: NotRequired[dict[str, float]]
    """The usage data of this word, as described in the Toki Pona Dictionary."""
    parent_id: NotRequired[str]
    """The most widely used word which is considered to be an exact synonym for this word."""
    see_also: list[str]
    """The IDs of words related to this one."""
    resources: FieldSchema20
    representations: FieldSchema24
    source_language: str
    """The language this word originated from"""
    usage_category: FieldSchema36
    deprecated: bool
    """Whether this word is considered deprecated by its author(s)."""
    audio: list[FieldSchema38Item]
    pu_verbatim: NotRequired[FieldSchema41]
    usage: dict[str, float]
    """The percentage of respondents to the annual Linku word survey who report to use this word, by the date of the survey."""
    glyph_ids: list[str]
    """The IDs of all sitelen pona glyphs which represent the word. The usage category of each fetched glyph may be used to show or hide glyphs."""
    primary_glyph_id: NotRequired[str]
    """The ID of the glyph most commonly used to represent this word in sitelen pona."""
    image: NotRequired[str]
    """Link to a PNG of the primary sitelen pona glyph for this word."""
    svg: NotRequired[str]
    """Link to an SVG of the primary sitelen pona glyph for this word."""
    translations: FieldSchema51


type Words = dict[str, FieldSchema1]
"""A raw data object containing dictionary info about Toki Pona words"""
