# generated by datamodel-codegen:
#   filename:  word.json

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

type FieldSchema1 = str
"""A unique identifier for an object in Linku. Generally named after the object."""


class FieldSchema7(StrEnum):
    """
    Which official Toki Pona book was this word featured in, if any.
    """

    pu = 'pu'
    ku_suli = 'ku suli'
    ku_lili = 'ku lili'
    none = 'none'


class FieldSchema8(StrEnum):
    """
    The period of time in which this word was coined, relative to the publication of the first two official Toki Pona books
    """

    pre_pu = 'pre-pu'
    post_pu = 'post-pu'
    post_ku = 'post-ku'


type FieldSchema11 = str


type FieldSchema14 = float


type FieldSchema28 = str


type FieldSchema30Item = str


class FieldSchema35(StrEnum):
    """
    The word's usage category, derived from the data of the annual Linku word survey.
    """

    core = 'core'
    common = 'common'
    uncommon = 'uncommon'
    obscure = 'obscure'
    sandbox = 'sandbox'


type FieldSchema44 = str


@dataclass
class FieldSchema50:
    commentary: str
    """Localized commentary on this word, such as history, clarifications, or trivia."""
    etymology: str
    """Localized etymology of this word."""
    definition: str
    """Localized definition of this word."""


@dataclass
class FieldSchema37Item:
    """Audio files of the words pronounced out loud"""

    author: str
    """The author of the audio file in `link`."""
    link: str
    """A link to the audio file for the word, pronounced by `author`."""


@dataclass
class FieldSchema41:
    en: str
    """The word's definition in the English edition of Toki Pona: The Language of Good"""
    fr: str
    """The word's definition in the French edition of Toki Pona: The Language of Good"""
    de: str
    """The word's definition in the German edition of Toki Pona: The Language of Good"""
    eo: str
    """The word's definition in the Esperanto edition of Toki Pona: The Language of Good"""


@dataclass
class FieldSchema19:
    """Non-Linku resources related to the specific word, such as wiki links."""

    sona_pona: str | None = None
    """A link to the word's page on sona.pona.la, a Toki Pona wiki. May redirect for words with references but no dedicated page."""
    lipamanka_semantic: str | None = None
    """A link to lipamanka's description of the word's semantic space."""


type FieldSchema40 = FieldSchema41
"""The definition of the word in specific language editions of Toki Pona: The Language of Good"""


@dataclass
class FieldSchema23:
    """Ways of representing this word via text/computers"""

    sitelen_emosi: str | None = None
    """The sitelen emosi representation of this word, a script for writing Toki Pona using emoji"""
    sitelen_jelo: list[FieldSchema28] | None = None
    """One or more example emojis for how the word can be written in sitelen jelo"""
    ligatures: list[FieldSchema30Item] | None = None
    """A list of sitelen Lasina representations of the word, used by ligature fonts to visually convert latin characters into sitelen pona"""
    sitelen_sitelen: str | None = None
    """A URL pointing to an image of this word's sitelen sitelen hieroglyphic block"""
    ucsur: str | None = None
    """The UCSUR codepoint for this word."""


@dataclass
class Word:
    """General info on a Toki Pona word"""

    id: str
    """A unique identifier for the word. May have an integer to distinguish words with the same spelling but distinct coinings."""
    word: str
    """The latin alphabet representation of the word."""
    book: FieldSchema7
    coined_era: FieldSchema8
    creation_date: str
    """When this word was coined, to precision known."""
    author: list[FieldSchema11]
    """The name or names of those involved in creating this word."""
    see_also: list[FieldSchema1]
    """The IDs of words related to this one."""
    resources: FieldSchema19
    representations: FieldSchema23
    source_language: str
    """The language this word originated from"""
    usage_category: FieldSchema35
    deprecated: bool
    """Whether this word is considered deprecated by its author(s)."""
    audio: list[FieldSchema37Item]
    usage: dict[FieldSchema44, FieldSchema14]
    """The percentage of respondents to the annual Linku word survey who report to use this word, by the date of the survey."""
    glyph_ids: list[FieldSchema1]
    """The IDs of all sitelen pona glyphs which represent the word. The usage category of each fetched glyph may be used to show or hide glyphs."""
    translations: FieldSchema50
    author_verbatim: str | None = None
    """The author's original definition, taken verbatim in their words"""
    author_source: str | None = None
    """The source or origin of this glyph, often a URL."""
    ku_data: dict[str, FieldSchema14] | None = None
    """The usage data of this word, as described in the Toki Pona Dictionary."""
    parent_id: str | None = None
    """The most widely used word which is considered to be an exact synonym for this word."""
    pu_verbatim: FieldSchema40 | None = None
    primary_glyph_id: str | None = None
    """The ID of the glyph most commonly used to represent this word in sitelen pona."""
    image: str | None = None
    """Link to a PNG of the primary sitelen pona glyph for this word."""
    svg: str | None = None
    """Link to an SVG of the primary sitelen pona glyph for this word."""
